services:

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel-app
    working_dir: /var/www/
    volumes:
      - ./src:/var/www/
    ports:
      - "5173:5173" 
    networks:
      - laravel-net        
    depends_on:
      - mysql

  nginx:
    image: nginx:1.26
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/
    networks:
      - laravel-net            
    depends_on:
      - php

  mysql:
    image: mysql:8.0.42
    platform: linux/arm64/v8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"  # 本番環境では必要に応じて外部公開制限する
    command:
      --default-authentication-plugin=caching_sha2_password
    networks:
      - laravel-net

  phpmyadmin:
    platform: linux/amd64
    image: phpmyadmin/phpmyadmin
    container_name: laravel-phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=laravel_user
      - PMA_PASSWORD=laravel_pass
    depends_on:
      - mysql
    ports:
      - "8080:80"
    networks:
      - laravel-net

volumes:
  mysql_data:

networks:
  laravel-net:
