services:

  php:
    volumes:
      - ./src:/var/www/

  nginx:
    volumes:
      - ./src:/var/www:cached  # macOS で I/O 安定化
      - ./docker/nginx/nginx.mac.conf:/etc/nginx/nginx.conf:ro  # ←Mac版に差し替え
